from .vanilla_gan import *
from .dcgan import *
from .wgan import *
from .pix2pix import *
from .cyclegan import *
from .cgan import *
from .infogan import *
from .voxelgan import *
from .sagan import *
